name: Build MediaMod for Minecraft Forge

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
          curl -H "Content-Type: application/json" -X POST -d "{\"embeds\": [{\"title\": \"Building Mod\",\"color\": 3447003, \"description\": \"Building \`\`$COMMIT_DESCRIPTION\`\`\"}]}" $DISCORD_WEBHOOK
      - name: Download JDK 1.8 # actions/setup-java@v1 doesn't download it correctly, so we download it manually and pass the file to setup-java
        run: |
          wget -O jdk.tar.gz https://cdn.azul.com/zulu/bin/zulu8.40.0.25-ca-jdk8.0.222-linux_x64.tar.gz -o /dev/null
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          jdkFile: jdk.tar.gz
      - name: Build with Gradle
        run: ./gradlew build
      - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: .build/libs/MediaMod-1.1.0.jar
            prerelease: true
            body: "## MediaMod Beta\n🚀 This is a beta build! If you encounter bugs, please report them!\n*Automatically built by the CI System*"
            name: "MediaMod Beta Build"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_SECRET }}
      - name: Discord notification 2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_DESCRIPTION=$(git log --pretty=format:"%s by %an (%D)" -n 1)
          curl -H "Content-Type: application/json" -X POST -d "{\"embeds\": [{\"title\": \"Build Successful\",\"color\": 3066993, \"description\": \"Successfully built \`\`$COMMIT_DESCRIPTION\`\`\"}]}" $DISCORD_WEBHOOK
